#!/usr/local/bin/perl

###############################################################################
# $Id$
#
# SBEAMS is Copyright (C) 2000-2021 Institute for Systems Biology
# This program is governed by the terms of the GNU General Public License (GPL)
# version 2 as published by the Free Software Foundation.  It is provided
# WITHOUT ANY WARRANTY.  See the full description of GPL terms in the
# LICENSE file distributed with this software.
###############################################################################


###############################################################################
# Get the script set up with everything it will need
###############################################################################
use strict;
use CGI::Carp qw(fatalsToBrowser croak);
use Data::Dumper;

use lib qw (../../lib/perl);
use vars qw ($q $sbeams $sbeamsMOD $PROG_NAME
             $current_contact_id $current_username $glyco_query_o);
use SBEAMS::Connection qw($q $log);
use SBEAMS::Connection::Settings;
use SBEAMS::Connection::Tables;
use SBEAMS::Connection::DataTable;

use SBEAMS::BioLink::Tables;
use SBEAMS::BioLink::MSF;

use SBEAMS::PeptideAtlas;
use SBEAMS::PeptideAtlas::Settings;
use SBEAMS::PeptideAtlas::Tables;
use SBEAMS::PeptideAtlas::ProtInfo;
use SBEAMS::Connection::TabMenu;


###############################################################################
# Global Variables
###############################################################################
#
$sbeams = new SBEAMS::Connection;
$sbeamsMOD = new SBEAMS::PeptideAtlas;
$sbeamsMOD->setSBEAMS($sbeams);

$sbeams->setSBEAMS_SUBDIR($SBEAMS_SUBDIR);

{ # Main 

  # Authenticate or exit
  $current_username = $sbeams->Authenticate(allow_anonymous_access=>1) || exit;
  #### Read in the default input parameters
  my %params;
  $sbeams->parse_input_parameters( q=>$q, parameters_ref=>\%params );
  $sbeams->processStandardParameters(parameters_ref=>\%params);

  ## get project_id to send to HTMLPrinter display
  my $project_id = $sbeams->getCurrent_project_id();

  my $page = $sbeams->getGifSpacer( 800 ) . "<br>\n";

  my $tabMenu = $sbeamsMOD->getTabMenu(
    parameters_ref => \%params,
    program_name => 'GetProtein',
      );
  $page .= "$tabMenu";


  $sbeamsMOD->display_page_header(project_id => $project_id);
  my $curr_bid = $sbeamsMOD->getCurrentAtlasBuildID( parameters_ref => \%params );
  my $msg = $sbeams->update_PA_table_variables($curr_bid);

  $log->debug( "Begin page:" .time() );
  my @select = $sbeamsMOD->GetBuildSelect( set_onchange => 1,
             build_id => $curr_bid,
             form_name => 'compareProteins' );
  $page .= $select[1];
  $page .= "<br><p><form method='post' name='compareProteins'>\n";
  $page .= "$select[0]\n";

  if ( $params{bioseq_id} || $params{restore} || $params{protein_list} ||
       $params{protein_group_number} || $params{protein_list_id} ) {
    #$page .= get_alignment_display( %params );
    $page .= $sbeamsMOD->get_alignment_display(  %params,
                                                 order_by => 'dup',  
                                                 atlas_build_id => $curr_bid);
  } else {
    $page .= "</form></p>\n";
    $page .= $sbeams->makeErrorText( "Missing required parameter bioseq_id or protein_group_number" );
  }

  $log->debug( "Page done:" .time() );

  # Display page
  print $page;
  $sbeamsMOD->display_page_footer();
} # end main


